#include <stdio.h>
#include <stdlib.h>
int main(){
	printf("begin");
	for(int i = 0; i <2000; ++i){
		char *str;
	str = (char *) malloc(6001);
   strcpy(str, "tutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspointtutorialspoint");
}
}
